/* GENERATED BY make_primitives_header.py in Makefile. DO NOT EDIT */


const int NUM_OPS=12;



enum OPS { NOOP_=0,X_=1,ZERO_=2,ONE_=3,EXP_=4,NEG_=5,LOG_=6,MUL_=7,ADD_=8,SUB_=9,DIV_=10,POW_=11};



__device__ const int NARGS[]  = {0, 0,0,0,1,1,1,2,2,2,2,2 };
 const int hNARGS[] = {0, 0,0,0,1,1,1,2,2,2,2,2 };
 const char* NAMES[] = { "<NA>", "x","zero","one","exp","neg","log","mul","add","sub","div","pow" };

 // Non-defined primitives, used potentially by print_program_as_expression

#define CONSTANT_ -99
