/* GENERATED BY make_primitives_header.py in Makefile. DO NOT EDIT */


const int NUM_OPS=12;



enum OPS { NOOP_=0,CONSTANT_=1,X_=2,ONE_=3,EXP_=4,NEG_=5,LOG_=6,ADD_=7,SUB_=8,DIV_=9,MUL_=10,POW_=11};



__device__ const int NARGS[]  = {0, 0,0,0,1,1,1,2,2,2,2,2 };
 const int hNARGS[] = {0, 0,0,0,1,1,1,2,2,2,2,2 };
 const char* NAMES[] = { "<NA>", "constant","x","one","exp","neg","log","add","sub","div","mul","pow" };
