/* GENERATED BY make_primitives_header.py in Makefile. DO NOT EDIT */


	case ONE_: stack[newtop] = 1.0f; break;
	case X_: stack[newtop] = X; break;
	case EXP_: stack[newtop] = my_exp(stack[top]); break;
	case NEG_: stack[newtop] = my_neg(stack[top]); break;
	case LOG_: stack[newtop] = my_log(stack[top]); break;
	case ADD_: stack[newtop] = my_add(stack[top], stack[top-1]); break;
	case SUB_: stack[newtop] = my_add(stack[top], -stack[top-1]); break;
	case DIV_: stack[newtop] = my_div(stack[top], stack[top-1]); break;
	case MUL_: stack[newtop] = my_mul(stack[top], stack[top-1]); break;
	case POW_: stack[newtop] = my_pow(stack[top], stack[top-1]); break;
